# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'girlfriendOfLangWang' do

pod 'TOMSMorphingLabel', '~> 0.5.1'
pod 'VBFPopFlatButton', '~> 0.0.6'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'EAIntroView', '~> 2.8.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ASValueTrackingSlider', '~> 0.11.2'

end

